// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookStoreWASM.Server.Models
{
    public partial class Book
    {
        public int BookId { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public decimal Price { get; set; }
        public string BookDescription { get; set; }
        public int Quantity { get; set; }
        public string CoverLink { get; set; }
        public string UserName { get; set; }
        public string Genres { get; set; }
    }
}